# Generated by Django 4.0.10 on 2024-06-10 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0002_customgroup_user'),
        ('course_management', '0001_initial'),
        ('university_management', '0004_alter_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.campus')),
            ],
        ),
        migrations.CreateModel(
            name='CLOUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('clos', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseinformation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.customgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('clo_update_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_process.cloupdaterequest')),
                ('current_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_process.approvalstep')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalChainStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('approval_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_process.approvalchain')),
                ('approval_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_process.approvalstep')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='approvalchain',
            name='steps',
            field=models.ManyToManyField(through='approval_process.ApprovalChainStep', to='approval_process.approvalstep'),
        ),
    ]
