# Generated by Django 4.0.10 on 2024-06-08 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_management', '0004_alter_section_name'),
        ('course_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='clo',
            field=models.ManyToManyField(related_name='questions', to='course_management.courselearningoutcomes'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='university_management.batch'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='course_management.courseinformation'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
