# Generated by Django 4.0.10 on 2024-04-04 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='custom_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
