# Generated by Django 4.0.10 on 2024-04-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_management', '0002_remove_batch_sections_batchsection'),
        ('program_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plo',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university_management.department'),
        ),
    ]
