# Generated by Django 4.0.10 on 2024-04-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_management', '0004_remove_plo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plo',
            name='name',
            field=models.CharField(default='h', max_length=50, null=True),
        ),
    ]
