# Generated by Django 4.0.10 on 2024-05-01 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program_management', '0007_remove_plo_program_alter_peo_description_and_more'),
        ('university_management', '0002_remove_batch_sections_batchsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('theory_credits', models.IntegerField()),
                ('lab_credits', models.IntegerField()),
                ('course_type', models.CharField(max_length=20)),
                ('required_elective', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='course_management.courseinformation')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.university')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLearningOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bloom_taxonomy', models.CharField(choices=[('Cognitive', 'Cognitive'), ('Psychomotor', 'Psychomotor'), ('Affective', 'Affective')], max_length=20)),
                ('level', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseinformation')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseinformation')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4'), (5, 'Week 5'), (7, 'Week 7'), (8, 'Week 8'), (10, 'Week 10'), (11, 'Week 11'), (13, 'Week 13'), (14, 'Week 14'), (15, 'Week 15'), (16, 'Week 16')])),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assessments', models.TextField()),
                ('clo', models.ManyToManyField(to='course_management.courselearningoutcomes')),
                ('course_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_hours_per_week', models.IntegerField()),
                ('lab_hours_per_week', models.IntegerField()),
                ('discussion_hours_per_week', models.IntegerField()),
                ('office_hours_per_week', models.IntegerField()),
                ('course_outline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseinformation')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseinformation')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('book_type', models.CharField(choices=[('Reference', 'Reference'), ('Text', 'Text')], max_length=20)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('course_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clo', models.ManyToManyField(to='course_management.courselearningoutcomes')),
                ('course_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseoutline')),
            ],
        ),
        migrations.CreateModel(
            name='PLO_CLO_Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courselearningoutcomes')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program_management.plo')),
            ],
            options={
                'unique_together': {('plo', 'clo')},
            },
        ),
    ]
