# Generated by Django 4.0.10 on 2024-04-18 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university_management', '0002_remove_batch_sections_batchsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=255)),
                ('assignments', models.IntegerField()),
                ('lab_reports', models.IntegerField(default=0)),
                ('design_reports', models.IntegerField(default=0)),
                ('quizzes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('theory_credits', models.IntegerField()),
                ('lab_credits', models.IntegerField()),
                ('course_type', models.CharField(max_length=20)),
                ('required_elective', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='course_management.courseinformation')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLearningOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('bloom_taxonomy', models.CharField(choices=[('Cognitive', 'Cognitive'), ('Psychomotor', 'Psychomotor'), ('Affective', 'Affective')], max_length=20)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_hours_per_week', models.IntegerField(default=2)),
                ('lab_hours_per_week', models.IntegerField(default=0)),
                ('discussion_hours_per_week', models.IntegerField(default=1)),
                ('office_hours_per_week', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='course_management.book')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='course_management.book')),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizzes_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('assignments_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mid_term_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('final_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('course_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseassessment')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.batch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='course_management.courseinformation')),
            ],
        ),
    ]
