# Generated by Django 4.0.10 on 2024-05-01 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('book_type', models.CharField(choices=[('Reference', 'Reference'), ('Text', 'Text')], max_length=20)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('course_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.courseoutline')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseBook',
        ),
    ]
