# Generated by Django 4.0.10 on 2024-05-03 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_management', '0002_remove_batch_sections_batchsection'),
        ('course_management', '0003_alter_courseoutline_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinformation',
            name='university',
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='campus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='university_management.campus'),
        ),
    ]
