# Generated by Django 4.0.10 on 2024-04-18 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='sections',
        ),
        migrations.CreateModel(
            name='BatchSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.batch')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_management.section')),
            ],
            options={
                'unique_together': {('batch', 'section')},
            },
        ),
    ]
