# Generated by Django 4.0.10 on 2024-05-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_management', '0002_remove_batch_sections_batchsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='sections',
            field=models.ManyToManyField(to='university_management.section'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='university_management.department'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'department')},
        ),
        migrations.DeleteModel(
            name='BatchSection',
        ),
    ]
