# Generated by Django 4.0.10 on 2024-05-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_management', '0003_batch_sections_alter_batch_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
